language: php

php:
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - composer self-update
  - cd ..
  - cp extbase_language_tests/Build/composer.json .
  - composer --dev install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv extbase_language_tests typo3conf/ext/extbase_language_tests

script:
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    ./bin/phpunit --colors --process-isolation --bootstrap ./typo3/sysext/core/Build/FunctionalTestsBootstrap.php -c ./typo3conf/ext/extbase_language_tests/Build/FunctionalTests.xml
